export const copy = {
  en: {
    description: 'Omasend is a file-sharing app built for Omarchy. It speaks the LocalSend protocol, so it sends files, screenshots, recordings and text to any LocalSend app on your local network.',
    skip: 'Skip to content', download: 'Download', source: 'Source', theme: 'Theme', language: 'Language', darkMode: 'Dark mode', nav: 'Main navigation',
    eyebrow: 'Made for Omarchy', title: 'Copy. Paste. Send.',
    intro: 'Omasend brings files, screenshots and text from your Omarchy desktop to your other devices. It speaks the LocalSend protocol, so every LocalSend app is already a device you can reach.',
    get: 'Get Omasend', explore: 'See how it works', note: 'LocalSend protocol · Local network · No account',
    screenshot: 'Omasend on Omarchy, with nearby devices and a drop area for files and clipboard content',
    illustration: 'Files travel directly between devices on your local network.',
    local: 'Your local network', desktop: 'Your desktop', peer: 'Nearby device', payload: 'screenshot.png',
    workflow: 'One familiar gesture.', workflowIntro: 'A screenshot, a recording, a folder, a thought. Everything starts in the same composer.',
    steps: [
      ['Copy something.', 'Copy an image, a file or some text. You can also drag files and folders into Omasend.'],
      ['Choose a device.', 'Open Omasend or LocalSend on your other device, on the same network. Nearby devices appear automatically.'],
      ['Send it over.', 'Preview what you’re sending. Your recipient accepts the transfer; received files go to Downloads.'],
    ],
    details: 'A small app. A clear purpose.',
    facts: [
      ['Works with every LocalSend app', 'Omasend speaks the LocalSend protocol. LocalSend on Android, iOS, macOS, Windows or Linux shows up here as a nearby device, and Omasend shows up there. The same protocol on both ends, with nothing in between.'],
      ['Copy, paste, send', 'A screenshot, a recording, a folder or a few words. Paste what you have, drag it in, or pick files, and preview everything before it leaves.'],
      ['You accept what arrives', 'Nothing lands unannounced. Accept or decline each incoming transfer; received files go to Downloads without overwriting what is already there.'],
      ['Follow every transfer', 'Progress and speed while a transfer runs, a cancel button when you change your mind, and a history of the current session.'],
      ['Encrypted and local', 'Transfers go directly between devices over HTTPS, with a certificate pinned to each device. No account, and no cloud upload.'],
      ['At home on Omarchy', 'Your desktop theme, familiar shortcuts, and a compact interface. English or 简体中文, and updates from the menu.'],
    ],
    protocol: 'Omasend speaks the LocalSend protocol, version 2.2, through the same Rust core LocalSend itself runs on. Devices announce themselves over multicast on port 53317, and files travel over HTTPS.',
    protocolLink: 'LocalSend protocol',
    install: 'Make room for one less step.', installIntro: 'Choose a desktop build, or install from your terminal.',
    releases: 'Browse releases', mac: 'Apple silicon · Intel', linux: 'x86_64 · ARM64 · Wayland', windows: 'x86_64',
    platform: 'Operating system', archive: 'Release archives', terminal: 'Terminal install', shell: 'macOS / Linux', powershell: 'Windows / PowerShell',
    copy: 'Copy', copied: 'Copied', copyFailed: 'Select and copy the command below.',
    prerelease: 'Development builds. Published downloads appear on GitHub Releases.',
    installNote: 'The installer selects your platform and verifies the release checksum.',
    sourceInstall: 'Build from source', script: 'Read the installer',
    footer: 'An independent community project.', built: 'Built with',
  },
  'zh-CN': {
    description: 'Omasend 是为 Omarchy 打造的文件分享应用，使用 LocalSend 协议，通过局域网将文件、截图、录屏和文字发送到任意 LocalSend 客户端。',
    skip: '跳转到内容', download: '下载', source: '源码', theme: '主题', language: '语言', darkMode: '深色模式', nav: '主导航',
    eyebrow: '为 Omarchy 而生', title: '复制 粘贴 发送',
    intro: '用 Omasend，把 Omarchy 桌面上的文件、截图和文字送到另一台设备。它使用 LocalSend 协议，所以每一个 LocalSend 客户端都是你可以直接发送的设备。',
    get: '获取 Omasend', explore: '了解使用方式', note: 'LocalSend 协议 · 局域网传输 · 无需账号',
    screenshot: 'Omarchy 桌面上的 Omasend，展示附近设备与文件、剪贴板内容发送区域',
    illustration: '文件通过局域网直接在设备之间传输。',
    local: '你的局域网', desktop: '你的电脑', peer: '附近设备', payload: 'screenshot.png',
    workflow: '一个熟悉的动作', workflowIntro: '截图、录屏、文件夹，或一段想法。都从同一个待发送区域开始。',
    steps: [
      ['复制内容', '复制图片、文件或文字，也可以把文件和文件夹直接拖进 Omasend。'],
      ['选择设备', '在同一网络的另一台设备上打开 Omasend 或 LocalSend。附近设备会自动出现。'],
      ['发送过去', '预览即将发送的内容。对方确认后开始传输，收到的文件直接保存到下载目录。'],
    ],
    details: '小巧的应用，明确的用途',
    facts: [
      ['与所有 LocalSend 客户端互通', 'Omasend 使用 LocalSend 协议。Android、iOS、macOS、Windows、Linux 上的 LocalSend 会作为附近设备出现在这里，Omasend 也会出现在它们那里。两端是同一套协议，中间不需要任何转换。'],
      ['复制、粘贴、发送', '截图、录屏、文件夹，或几句话。粘贴、拖入，或从文件选择器添加，发送前都可以先预览。'],
      ['收到什么由你决定', '不会有内容悄悄进来。每一次接收都由你确认或拒绝，收到的文件保存到下载目录，不会覆盖已有文件。'],
      ['掌握每一次传输', '传输过程中可以看到进度和速度，改主意时随时取消，本次会话的收发记录也一并保留。'],
      ['加密，且不出局域网', '内容通过 HTTPS 直接在设备之间传输，证书按设备指纹绑定。无需账号，也不上传云端。'],
      ['融入 Omarchy 桌面', '跟随桌面主题，使用熟悉的快捷键，保持紧凑的界面。支持 English 与简体中文，也可以从菜单检查更新。'],
    ],
    protocol: 'Omasend 使用 LocalSend 协议 2.2 版，底层是 LocalSend 自己的 Rust core。设备通过 53317 端口的组播互相发现，文件经 HTTPS 传输。',
    protocolLink: 'LocalSend 协议',
    install: '让分享少一个步骤', installIntro: '选择桌面版本，或通过终端安装。',
    releases: '查看发布版本', mac: 'Apple 芯片 · Intel', linux: 'x86_64 · ARM64 · Wayland', windows: 'x86_64',
    platform: '操作系统', archive: '发行包', terminal: '终端安装', shell: 'macOS / Linux', powershell: 'Windows / PowerShell',
    copy: '复制', copied: '已复制', copyFailed: '请选择并复制下方命令。',
    prerelease: '开发阶段。已发布的下载包会列在 GitHub Releases。',
    installNote: '安装脚本会选择对应平台，并校验发行包的校验和。',
    sourceInstall: '从源码构建', script: '查看安装脚本',
    footer: '独立社区项目。', built: '构建于',
  },
} as const;
