export const copy = {
  en: {
    description: 'OmaSend is a native desktop LocalSend client built for Omarchy. Send files, screenshots, recordings and text across your local network.',
    skip: 'Skip to content', download: 'Download', source: 'Source', theme: 'Theme', language: 'Language', darkMode: 'Dark mode', nav: 'Main navigation',
    eyebrow: 'Native to your desktop.', title: 'Copy. Paste. Send.',
    intro: 'The things on your screen, on your other device. A native LocalSend client, built with GPUI Kit and GPUI Omarchy.',
    get: 'Get OmaSend', explore: 'See how it works', note: 'Local network · Open source · No account',
    illustration: 'Files travel directly between devices on your local network.',
    local: 'Your local network', desktop: 'Your desktop', peer: 'Nearby device', payload: 'screenshot.png',
    workflow: 'One familiar gesture.', workflowIntro: 'A screenshot, a recording, a folder, a thought. Everything starts in the same composer.',
    steps: [
      ['Copy something.', 'Copy an image, a file or some text. You can also drag files and folders into OmaSend.'],
      ['Choose a device.', 'Open LocalSend on your other device, on the same network. Nearby devices appear automatically.'],
      ['Send it over.', 'Preview what you’re sending. Your recipient accepts the transfer; received files go to Downloads.'],
    ],
    details: 'A small app. A clear purpose.',
    facts: [
      ['Your clipboard comes first', 'Wayland clipboard types are read before the content. Images stay images. File links point to the original file.'],
      ['Built with GPUI Kit', 'GPUI Kit provides the native Rust UI foundation. GPUI Omarchy supplies components that follow your desktop theme, with keyboard-first interactions.'],
      ['LocalSend underneath', 'The official LocalSend Rust core handles discovery and HTTPS transfers. Your data stays on the local network.'],
      ['Open when you need it', 'No account, cloud service or background daemon. Close the app and it leaves the network.'],
    ],
    install: 'Make room for one less step.', installIntro: 'Choose a desktop build, or install from your terminal.',
    releases: 'Browse releases', mac: 'Apple silicon · Intel', linux: 'x86_64 · Wayland', windows: 'x86_64',
    platform: 'Operating system', archive: 'Release archives', terminal: 'Terminal install', shell: 'macOS / Linux', powershell: 'Windows / PowerShell',
    copy: 'Copy', copied: 'Copied', copyFailed: 'Select and copy the command below.',
    prerelease: 'Development builds. Published downloads appear on GitHub Releases.',
    installNote: 'The installer selects your platform and verifies the release checksum.',
    sourceInstall: 'Build from source', script: 'Read the installer',
    footer: 'An independent community project.', built: 'Built with',
  },
  'zh-CN': {
    description: 'OmaSend 是为 Omarchy 打造的原生 LocalSend 桌面客户端，在局域网内发送文件、截图、录屏和文字。',
    skip: '跳转到内容', download: '下载', source: '源码', theme: '主题', language: '语言', darkMode: '深色模式', nav: '主导航',
    eyebrow: '为你的桌面而生', title: '复制 粘贴 发送',
    intro: '把屏幕上的内容，送到另一台设备。使用 GPUI Kit 与 GPUI Omarchy 构建的原生 LocalSend 客户端。',
    get: '获取 OmaSend', explore: '了解使用方式', note: '局域网传输 · 开源 · 无需账号',
    illustration: '文件通过局域网直接在设备之间传输。',
    local: '你的局域网', desktop: '你的电脑', peer: '附近设备', payload: 'screenshot.png',
    workflow: '一个熟悉的动作', workflowIntro: '截图、录屏、文件夹，或一段想法。都从同一个待发送区域开始。',
    steps: [
      ['复制内容', '复制图片、文件或文字，也可以把文件和文件夹直接拖进 OmaSend。'],
      ['选择设备', '在同一网络的另一台设备上打开 LocalSend。附近设备会自动出现。'],
      ['发送过去', '预览即将发送的内容。对方确认后开始传输，收到的文件直接保存到下载目录。'],
    ],
    details: '小巧的应用，明确的用途',
    facts: [
      ['从剪贴板开始', '先识别 Wayland 剪贴板类型，再读取内容。图片保持为图片，文件链接直接指向原文件。'],
      ['使用 GPUI Kit 构建', 'GPUI Kit 提供原生 Rust 界面基础，GPUI Omarchy 提供跟随桌面主题的组件与键盘交互。'],
      ['基于 LocalSend', '官方 LocalSend Rust core 负责设备发现与 HTTPS 传输。数据留在局域网内。'],
      ['需要时才打开', '无需账号、云服务或后台守护进程。退出应用，便从网络中离开。'],
    ],
    install: '让分享少一个步骤', installIntro: '选择桌面版本，或通过终端安装。',
    releases: '查看发布版本', mac: 'Apple 芯片 · Intel', linux: 'x86_64 · Wayland', windows: 'x86_64',
    platform: '操作系统', archive: '发行包', terminal: '终端安装', shell: 'macOS / Linux', powershell: 'Windows / PowerShell',
    copy: '复制', copied: '已复制', copyFailed: '请选择并复制下方命令。',
    prerelease: '开发阶段。已发布的下载包会列在 GitHub Releases。',
    installNote: '安装脚本会选择对应平台，并校验发行包的校验和。',
    sourceInstall: '从源码构建', script: '查看安装脚本',
    footer: '独立社区项目。', built: '构建于',
  },
} as const;
