export const copy = {
  en: {
    description: 'Omasend is a file-sharing app built for Omarchy. Send files, screenshots, recordings and text to your other devices over your local network.',
    skip: 'Skip to content', download: 'Download', source: 'Source', theme: 'Theme', language: 'Language', darkMode: 'Dark mode', nav: 'Main navigation',
    eyebrow: 'Made for Omarchy', title: 'Copy. Paste. Send.',
    intro: 'Omasend brings files, screenshots and text from your Omarchy desktop to your other devices. Paste, choose a device, and send over your local network.',
    get: 'Get Omasend', explore: 'See how it works', note: 'Local network · Open source · No account',
    screenshot: 'Omasend on Omarchy, with nearby devices and a drop area for files and clipboard content',
    illustration: 'Files travel directly between devices on your local network.',
    local: 'Your local network', desktop: 'Your desktop', peer: 'Nearby device', payload: 'screenshot.png',
    workflow: 'One familiar gesture.', workflowIntro: 'A screenshot, a recording, a folder, a thought. Everything starts in the same composer.',
    steps: [
      ['Copy something.', 'Copy an image, a file or some text. You can also drag files and folders into Omasend.'],
      ['Choose a device.', 'Open LocalSend on your other device, on the same network. Nearby devices appear automatically.'],
      ['Send it over.', 'Preview what you’re sending. Your recipient accepts the transfer; received files go to Downloads.'],
    ],
    details: 'A small app. A clear purpose.',
    facts: [
      ['At home on Omarchy', 'Your desktop theme, familiar shortcuts, and a compact interface. Omasend fits the way you use Omarchy.'],
      ['Copy, paste, send', 'A screenshot, a recording, a folder or a few words. Paste what you have, or drag it into Omasend.'],
      ['Reach your other devices', 'Share with Omasend and LocalSend on the same network. Nearby devices appear automatically.'],
      ['Keep it local', 'No account or cloud upload. Transfers go directly between devices, and you choose which incoming files to accept.'],
    ],
    install: 'Make room for one less step.', installIntro: 'Choose a desktop build, or install from your terminal.',
    releases: 'Browse releases', mac: 'Apple silicon · Intel', linux: 'x86_64 · ARM64 · Wayland', windows: 'x86_64',
    platform: 'Operating system', archive: 'Release archives', terminal: 'Terminal install', shell: 'macOS / Linux', powershell: 'Windows / PowerShell',
    copy: 'Copy', copied: 'Copied', copyFailed: 'Select and copy the command below.',
    prerelease: 'Development builds. Published downloads appear on GitHub Releases.',
    installNote: 'The installer selects your platform and verifies the release checksum.',
    sourceInstall: 'Build from source', script: 'Read the installer',
    footer: 'An independent community project.', built: 'Built with',
  },
  'zh-CN': {
    description: 'Omasend 是为 Omarchy 打造的文件分享应用，通过局域网将文件、截图、录屏和文字发送到你的其他设备。',
    skip: '跳转到内容', download: '下载', source: '源码', theme: '主题', language: '语言', darkMode: '深色模式', nav: '主导航',
    eyebrow: '为 Omarchy 而生', title: '复制 粘贴 发送',
    intro: '用 Omasend，把 Omarchy 桌面上的文件、截图和文字送到另一台设备。粘贴内容，选择设备，通过局域网发送。',
    get: '获取 Omasend', explore: '了解使用方式', note: '局域网传输 · 开源 · 无需账号',
    screenshot: 'Omarchy 桌面上的 Omasend，展示附近设备与文件、剪贴板内容发送区域',
    illustration: '文件通过局域网直接在设备之间传输。',
    local: '你的局域网', desktop: '你的电脑', peer: '附近设备', payload: 'screenshot.png',
    workflow: '一个熟悉的动作', workflowIntro: '截图、录屏、文件夹，或一段想法。都从同一个待发送区域开始。',
    steps: [
      ['复制内容', '复制图片、文件或文字，也可以把文件和文件夹直接拖进 Omasend。'],
      ['选择设备', '在同一网络的另一台设备上打开 LocalSend。附近设备会自动出现。'],
      ['发送过去', '预览即将发送的内容。对方确认后开始传输，收到的文件直接保存到下载目录。'],
    ],
    details: '小巧的应用，明确的用途',
    facts: [
      ['融入 Omarchy 桌面', '跟随桌面主题，使用熟悉的快捷键，保持紧凑的界面。Omasend 延续你在 Omarchy 上的使用习惯。'],
      ['复制、粘贴、发送', '截图、录屏、文件夹，或几句话。把内容粘贴或拖进 Omasend，就可以发送。'],
      ['连接你的其他设备', '与同一网络上的 Omasend 和 LocalSend 互传内容，附近设备会自动出现。'],
      ['内容留在局域网', '无需账号或上传云端，内容直接在设备之间传输。收到文件前，由你决定是否接收。'],
    ],
    install: '让分享少一个步骤', installIntro: '选择桌面版本，或通过终端安装。',
    releases: '查看发布版本', mac: 'Apple 芯片 · Intel', linux: 'x86_64 · ARM64 · Wayland', windows: 'x86_64',
    platform: '操作系统', archive: '发行包', terminal: '终端安装', shell: 'macOS / Linux', powershell: 'Windows / PowerShell',
    copy: '复制', copied: '已复制', copyFailed: '请选择并复制下方命令。',
    prerelease: '开发阶段。已发布的下载包会列在 GitHub Releases。',
    installNote: '安装脚本会选择对应平台，并校验发行包的校验和。',
    sourceInstall: '从源码构建', script: '查看安装脚本',
    footer: '独立社区项目。', built: '构建于',
  },
} as const;
